"""added private messages

Revision ID: aa43f4fcee76
Revises: a8c23362e8ea
Create Date: 2021-05-09 00:18:21.541624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa43f4fcee76'
down_revision = 'a8c23362e8ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receipient_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['receipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_created_on'), 'message', ['created_on'], unique=False)
    op.create_index(op.f('ix_message_updated_on'), 'message', ['updated_on'], unique=False)
    op.add_column('user', sa.Column('message_last_read', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'message_last_read')
    op.drop_index(op.f('ix_message_updated_on'), table_name='message')
    op.drop_index(op.f('ix_message_created_on'), table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###
